#%RAML 1.0 Trait
    responses:
      400:
        description: Invalid key/empty value
        body:
          application/json:
            example: |
              {
                "message": "bad request"
              }
      500:
        description: server issues
        body:
          application/json:
            example: |
              {
                 "message":  "Internal server error"   
              }